### PR TITLE
add google support for llm-client (aka llm-polyglot)

### PR DESCRIPTION
**Pull request by jcamera**
### llm-polyglot support for Google AI

This is using Google AI SDK (aka Gemini API) for Javascript - https://github.com/google-gemini/generative-ai-js

Be sure to set GOOGLE_API_KEY in your environment for use.

Features added:
 - Chat completion with support for message arrays conforming to OpenAI spec
   - google content array "parts" supports "model" (instead of "assistant") and "user", while system messages are may be included in the `systemInstruction` field
 - Support for streaming chat completion 
 - Function calling - streaming and non-streaming
 - Support for Google AI Cache Manager -  cache data may be added through `createCacheManager` and used by passing in the cache name from the response into `chat.completions.create` by setting it in `{ additionalProperties: cacheName }}` (*note:* this requires a paid account)

Note: polyfill added due to missing support for TextEncoderStream in bun.js (https://github.com/oven-sh/bun/issues/5648)

we may also consider using their Vertex AI API which has some tentative support for using OpenAI libraries with Gemini - https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-gemini-using-openai-library

or directly using their Gemini Rest API - https://ai.google.dev/api/rest

Feedback is welcome :-)

### CODE REVIEW

**Comment by ZECTBynmo** [comment]
Cool stuff @jcamera! Have you thought about how this might interact with/support the caching features that Gemini has? It'd be an awesome capability to add.

**Comment by jcamera** [comment]
> Cool stuff @jcamera! Have you thought about how this might interact with/support the caching features that Gemini has? It'd be an awesome capability to add.

Hey thank you @ZECTBynmo! I'm just getting my feet wet here, but I did look at an example using GoogleAICacheManager. We could totally add methods on the Google provider to support this, and use the same input data types as the chat completion.
And we could then add a param on chat.completions.create like { chat: name } using the name returned when the cache is set. This would diverge from the OpenAI spec a bit, but shouldn't hurt anything as an extra optional field. If OpenAI eventually adds a cache field we'd need to update. :-)
I can start adding this into this PR unless any objections.

**Comment by ZECTBynmo** [comment]
> I can start adding this into this PR unless any objections.

Awesome!

**Comment by jcamera** [comment]
Hi @ZECTBynmo, fyi I added some pieces to allow using the Google cache manager. (A paid account is needed to use it) Added an example in /examples. I'd be curious to learn about your use cases, and happy to help if any issues! 🙂

**Pull request closed without merging**
